const { registryServer } = require('micro-js')
console.log({process.argv})
const args = Array.prototype.slice.call(process.argv)
if (!args[2]) throw new Error('Specify "port" as first argument')
registryServer(args[2])
.catch(err => console.error(err))
