
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: registry
        image: gcr.io/micro-js/registry
      - name: service1
        image: gcr.io/micro-js/service1
      - name: service2
        image: gcr.io/micro-js/service2
      - name: service3
        image: gcr.io/micro-js/service3
---
apiVersion: apps/v1beta1
kind: Ingress
metadata:
  name: micro-js
  labels:
    app: nginx
spec:
  rules:
  - host: registry
    http:
      paths:
      - backend:
          serviceName: registry
          servicePort: 10000
  - host: service1
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 10001
  - host: service2
    http:
      paths:
      - backend:
          serviceName: service2
          servicePort: 10002
  - host: service3
    http:
      paths:
      - backend:
          serviceName: service3
          servicePort: 10003
