
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: registry
        image: gcr.io/micro-js/registry
        ports:
        - containerPort: 10000
      - name: service1
        image: gcr.io/micro-js/service1
        ports:
        - containerPort: 10001
      - name: service2
        image: gcr.io/micro-js/service2
        ports:
        - containerPort: 10002
      - name: service3
        image: gcr.io/micro-js/service3
        ports:
        - containerPort: 10003
---
apiVersion: apps/v1beta1
kind: Ingress
metadata:
  name: micro-js
  labels:
    app: nginx
spec:
  rules:
  - host: mcbrumagin.com
    http:
      paths:
      - backend:
          serviceName: registry
          servicePort: 10000
      - backend:
          serviceName: service1
          servicePort: 10001
      - backend:
          serviceName: service2
          servicePort: 10002
      - backend:
          serviceName: service3
          servicePort: 10003
