apiVersion: v1
kind: Pod
metadata:
  name: services
  labels:
    name: services
spec:
  hostNetwork: true
  containers:
    - name: service1
      image: gcr.io/micro-188415/service1
      env:
        - name: "SERVICE_REGISTRY_HOST"
          value: "35.227.106.175:10000" # TODO kubernetes config map (create config map from literal values)
    - name: service2
      image: gcr.io/micro-188415/service2
      env:
        - name: "SERVICE_REGISTRY_HOST"
          value: "35.227.106.175:10000"
    - name: service3
      image: gcr.io/micro-188415/service3
      env:
        - name: "SERVICE_REGISTRY_HOST"
          value: "35.227.106.175:10000"
